services:
  backend:
    build: ./backend
    container_name: envanter-backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/data:/app/data # SQLite veritabanı kalıcılığı için

  frontend:
    build: ./frontend
    container_name: envanter-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3001 # Production'da domain adı yazılmalı
